# Generated by Django 5.1.6 on 2025-02-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
